name: clean_architecture_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #networking:
  retrofit: ^4.0.1
  dio: ^5.1.2

  #state management
  flutter_bloc: ^8.1.2

  get_it: ^7.2.0
  floor: ^1.4.1
  flutter_hooks: ^0.18.6
  equatable: ^2.0.5
  oktoast: ^3.3.1
  auto_route: ^7.2.0
  awesome_dio_interceptor: 1.0.0

  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.0.1
  mockito: ^5.4.1
  #retrofit
  auto_route_generator: ^7.1.1
  retrofit_generator: ^6.0.0+1

  floor_generator: ^1.4.1
  build_runner: ^2.3.3
  bloc_test: ^9.1.2



flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
