// Mocks generated by Mockito 5.4.1 from annotations
// in clean_architecture_flutter/test/unit_test/presentation/cubits/remote_articles/remote_artilces_cubit_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:clean_architecture_flutter/src/domain/models/requests/breaking_news_request.dart'
    as _i6;
import 'package:clean_architecture_flutter/src/domain/models/responses/breaking_news_response.dart'
    as _i5;
import 'package:clean_architecture_flutter/src/domain/repositories/api_repository.dart'
    as _i3;
import 'package:clean_architecture_flutter/src/utils/resources/data_state.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRepository extends _i1.Mock implements _i3.ApiRepository {
  @override
  _i4.Future<_i2.DataState<_i5.BreakingNewsResponse>> getBreakingNewsArticles(
          {required _i6.BreakingNewsRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBreakingNewsArticles,
          [],
          {#request: request},
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.BreakingNewsResponse>>.value(
            _FakeDataState_0<_i5.BreakingNewsResponse>(
          this,
          Invocation.method(
            #getBreakingNewsArticles,
            [],
            {#request: request},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DataState<_i5.BreakingNewsResponse>>.value(
                _FakeDataState_0<_i5.BreakingNewsResponse>(
          this,
          Invocation.method(
            #getBreakingNewsArticles,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.BreakingNewsResponse>>);
}
